# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: ['--keep-runtime-typing', '--py311-plus']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        # warn-unused-ignores is unsafe with pre-commit, see
        # https://github.com/python/mypy/issues/2960
        args: ['--no-warn-unused-ignores', '--ignore-missing-imports']
        additional_dependencies:
          - flask
          - sqlalchemy
          - toml
          - tomli
          - types-python-dateutil
          - types-pytz
          - types-requests
          - types-setuptools
          - typing-extensions
  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.3
    hooks:
      - id: pylint
        args: [
            '--disable=import-error',
            '-rn', # Disable full report
            '-sn', # Disable evaluation score
            '--ignore-paths=migrations',
          ]
        additional_dependencies:
          - tomli
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        language_version: python3
        args: ['-c', 'pyproject.toml']
        additional_dependencies:
          - 'bandit[toml]'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ['--single-quote', '--trailing-comma', 'es5']
        exclude: funnel/templates/js/
